import type { NextPage } from 'next';
import Head from 'next/head';
import ProfileSide from '../components/ProfileSide';

const Home: NextPage = () => {
    return (
        <div className='main'>
            <Head>
                <title>KT Social</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className='app overflow-hidden text-primary-black bg-[#f3f3f3] p-4 '>
                <div className='blur-3xl absolute w-80 h-56 bg-[#a6ddf0] rounded-[50%] top-[-18%] right-0'></div>
                <div className='blur-3xl absolute w-80 h-56 bg-[#a6ddf0] rounded-[50%] top-[36%] left-[8rem]'></div>
                <div className='relative grid-cols-[20rem_auto_20rem] grid gap-4 Home'>
                    <ProfileSide/>
                    <div className='postSide '>post</div>
                    <div className='rightSide'>rightside</div>
                </div>
            </main>
        </div>
    );
};

export default Home;
